chatapp/urls.py
from django.urls import path
from .views import index, room

app_name = 'chatapp'

urlpatterns = [
    path('', index, name='chat'),
     path('<str:room_name>/', room, name='room'),
]

instagramproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('usersapp.urls', 'usersapp')),
    path('', include('instagramapp.urls', 'instagramapp')),
    path('chat/', include('chatapp.urls', 'chatapp')),
    path('', include('django.contrib.auth.urls')),
    path('api/v1', include('instagramapp.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),

   
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

usersapp/urls.py
from . import views as my_views
from django.contrib.auth import views
from django.urls import path
app_name = 'usersapp'

urlpatterns = [
    path('', views.LoginView.as_view(template_name='usersapp/login.html'), name='login'),
    path('logout', my_views.logout, name='logout'),
    path('signup/', my_views.signup, name='signup'),
    path('password_change/', views.PasswordChangeView.as_view(template_name='usersapp/password_change.html'), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(template_name='usersapp/password_change_done.html'), name='password_change_done'),
    path('password_reset/', views.PasswordResetView.as_view(template_name='usersapp/password_reset_form.html', html_email_template_name='usersapp/password_reset_email.html'), {"post_change_redirect":"password_reset/done"}, name='password_reset'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name='usersapp/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name='usersapp/password_reset_done.html'), name='password_reset_done'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='usersapp/password_reset_complete.html'), name='password_reset_complete'),
]

usersapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    profile_image = models.ImageField(upload_to='media/img', blank=True, null=True)

    def __str__(self):
        return self.user.username


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = Profile.objects.create(user=kwargs['instance'])
post_save.connect(create_profile, sender=User)



   

usersapp/forms.py
from django import forms
from django.contrib.auth import authenticate, login 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

#get form from user creationform
class SignUpForm(UserCreationForm):
    #add new attributes to the form
    email = forms.EmailField()
    class Meta:
        #when we save something with this form, we will modify user model
        model = User
        # specify the fields and the order so it shows up in the form
        fields = ["username", "email", "password1", "password2"]

usersapp/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from .forms import SignUpForm
from django.contrib.auth import logout as dj_logout
from .tasks import send_email

def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            email = request.POST['email']
            send_email(email)
            return HttpResponseRedirect(reverse('instagramapp:post_list'))
    else:
        form = SignUpForm()
    return render(request, 'usersapp/signup.html', {'form': form})


def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('usersapp:login'))

usersapp/templates/usersapp/base.html
{% load static %}

<head>
    <title>Instagram</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css" />
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans+Condensed&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/instagram.css' %}" />
</head>

<body>
    <div class="page-header">
        <h1><a href="{% url 'usersapp:login' %}">Instagram</a></h1>
        
         
    </div>
    <div class="content container">
        <div class="row">
        <div class="centeredForm">
            
                {% block content %} 
                {% endblock %}
           </div>
        </div>
    </div>
</body>

usersapp/templates/usersapp/login.html
{% extends "usersapp/base.html" %} 
{% load static %}

{% block content %}
<h1>Login</h1>
{% load crispy_forms_tags %}
<form action="" method="POST">
{% csrf_token %}
{% if error %} <p class="error">oops</p> 
{% endif %}
{{ form|crispy }}
<!-- <input type="hidden" name="next" value="{{ next }}"/> -->
<input type="submit" name="submit" class="button" value="Log in"/>
<div class="centered"><a href="{% url 'usersapp:password_reset' %}">Reset password</a></div>
<div class="centered"><a href="{% url 'usersapp:signup' %}">Dont have a user?</a></div>
</form>
{% endblock %}

usersapp/templates/usersapp/logout.html
<html>
<p>You are logged out. To log in again, click <a href="/">here</a>.</p> 
</html>

usersapp/templates/usersapp/password_change.html
{% block content %}


{% load crispy_forms_tags %}
<form method="POST">
    {% csrf_token %}
    <!-- this modifies form to lok nicer -->
    {{form| crispy}}
    <button type="submit">Update password</button>

    {% for field in form %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    {% endfor %}

</form>



{% endblock %}

usersapp/templates/usersapp/password_change_done.html
{% block content %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="m-auto">Your password has been set. You may go ahead and <a href="/">log in</a> now.</p>
	</div>
</div>

{% endblock %}

usersapp/templates/usersapp/password_reset_complete.html
{% block title %}Password reset complete{% endblock %}

{% block content %}
<h1>Password reset complete</h1>
<p>Your new password has been set. You can log in now on the <a href="{% url '' %}">log in page</a>.</p>
{% endblock %}

usersapp/templates/usersapp/password_reset_confirm.html
{% block title %}Enter new password{% endblock %}

{% block content %}

{% if validlink %}
{% load crispy_forms_tags %}

<h1>Set a new password!</h1>
<form method="POST">
  {% csrf_token %}
  {{ form|crispy}}
  <input type="submit" value="Change my password">
</form>

{% else %}

<p> "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." </p>

{% endif %}
{% endblock %}

usersapp/templates/usersapp/password_reset_done.html
{% extends "usersapp/base.html" %} 
{% load static %} 

{% block title %}Email Sent{% endblock %}

{% block content %}
  <h1>Check your inbox.</h1>
  <p>We've emailed you instructions for setting your password. You should receive the email shortly!</p>
{% endblock %}

usersapp/templates/usersapp/password_reset_email.html
<h1>To initiate the password reset process for your email {{email }},
click the link below:</h1>

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

<h1>If clicking the link above doesn't work, please copy and paste the URL in a new browser</h1>
window instead.

Sincerely,
The Unicorn Team

usersapp/templates/usersapp/password_reset_form.html
{% extends "usersapp/base.html" %} 
{% load static %}

{% block content %}
  <h1>Forgot your password?</h1>
  <p>Enter your email address below, and we'll email instructions for setting a new one.</p>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send me instructions!">
  </form>
{% endblock %}

usersapp/templates/usersapp/signup.html
{% extends "usersapp/base.html" %} 
{% load static %}

{% block content %}
    <h1>Create an account</h1>

    {% load crispy_forms_tags %}
    <form method="POST">
        {% csrf_token %}
        <!-- this modifies form to lok nicer -->
        {{form| crispy}}
        <button class="button" type="submit">Sign up</button>
    </form>

{% endblock %}

usersapp/templates/usersapp/signup_success.html
{% extends "usersapp/base.html" %} 
{% load static %}

{% block content %}
<div class="container">
	<div class="d-flex flex-column">
    <h1> Hooray! </h1>
		<p class="m-auto">You have successfully completed your signup. You may go ahead and <a href="/">log in</a> now.</p>
	</div>
</div>
{% endblock %}