chatapp/urls.py
from django.urls import path
from .views import index, room

app_name = 'chatapp'

urlpatterns = [
    path('', index, name='chat'),
     path('<str:room_name>/', room, name='room'),
]

instagramapp/urls.py
from django.urls import path
from . import views
from rest_framework.routers import SimpleRouter
from .views import UserProfileView, UserViewSet


app_name = 'instagramapp'

router = SimpleRouter()
router.register('users', UserViewSet, base_name='users')


urlpatterns = [
    path('post_list/', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('like_post', views.like_post, name='like_post'),
    path('profile/<int:pk>/',  UserProfileView.as_view(), name='profile'),
    path('users/',  UserViewSet.as_view({'get':'list'}), name='userview'),
    path('user_profile/',  views.user_profile, name='user_profile'),
    path('follow', views.follow, name="follow"),
    path('delete_post', views.delete_post, name="delete_post"),
    path('edit_profile', views.edit_profile, name="edit_profile"),
    path('connect/<operation>/<pk>/',  views.connect, name='connect'),
    ] 
urlpatterns += router.urls

instagramproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('usersapp.urls', 'usersapp')),
    path('', include('instagramapp.urls', 'instagramapp')),
    path('chat/', include('chatapp.urls', 'chatapp')),
    path('', include('django.contrib.auth.urls')),
    path('api/v1', include('instagramapp.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),

   
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

usersapp/urls.py
from . import views as my_views
from django.contrib.auth import views
from django.urls import path
app_name = 'usersapp'

urlpatterns = [
    path('', views.LoginView.as_view(template_name='usersapp/login.html'), name='login'),
    path('logout', my_views.logout, name='logout'),
    path('signup/', my_views.signup, name='signup'),
    path('password_change/', views.PasswordChangeView.as_view(template_name='usersapp/password_change.html'), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(template_name='usersapp/password_change_done.html'), name='password_change_done'),
    path('password_reset/', views.PasswordResetView.as_view(template_name='usersapp/password_reset_form.html', html_email_template_name='usersapp/password_reset_email.html'), {"post_change_redirect":"password_reset/done"}, name='password_reset'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name='usersapp/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name='usersapp/password_reset_done.html'), name='password_reset_done'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='usersapp/password_reset_complete.html'), name='password_reset_complete'),
]

instagramapp/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Follow(models.Model):
    following = models.ForeignKey(User, related_name="following", on_delete=models.CASCADE)
    follower = models.ForeignKey(User, related_name="follower", on_delete=models.CASCADE)
    
    def __str__(self):
        return self.following.username
  
    def loose_friend( follower, new_friend):
        follow = Follow.objects.get(
            follower = follower,
            following = new_friend
            )
        follow.delete()

    def make_friend( follower, new_friend):
        follow, created = Follow.objects.get_or_create(
            follower = follower,
            following = new_friend
            )
        follow.save()


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, blank=True)
    image = models.ImageField(upload_to='media/img', blank=True, null=True)
    likes = models.ManyToManyField(User, related_name ='likes', blank=True)
    created_date = models.DateTimeField(default=timezone.now) #auto_now_add=True
    published_date = models.DateTimeField(blank=True, null=True) #auto_now=True
   
    def __str__(self): 
        return self.title

    def total_likes(self):
        return self.likes.count()

    def publish(self):
        self.published_date = timezone.now()
        self.save()

instagramapp/forms.py
from django.forms import ModelForm
from .models import Post
from usersapp.models import Profile
from django.contrib.auth.models import User

class PostForm(ModelForm):
    class Meta:
        model=Post
        fields = {'image','title'}

class EditUserForm(ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name'
            )

class EditUserProfileForm(ModelForm):
    class Meta:
        model=Profile
        fields = (
            'bio',
            'profile_image',
            )

instagramapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.views.generic.base import TemplateView
from rest_framework import viewsets, generics

from .forms import PostForm, EditUserProfileForm, EditUserForm
from .models import Post, Follow
from .models import *
from .serializers import PostSerializer, UserSerializer
from .permissions import IsAuthorOrReadOnly

import requests

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    context={
        "posts" : posts,
        }
    if posts.exists():
        for post in posts:
            post.is_liked = False
            if post.likes.filter(id=request.user.id).exists():
                post.is_liked = True
            context={
                "posts" : posts,
                "is_liked" : post.is_liked,
                    }
    return render(request, 'instagramapp/index.html', context)


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True
    context={
        "post" : post,
        "is_liked" : is_liked,
        "total_likes": post.total_likes(),
    }
    return render(request, 'instagramapp/post_detail.html', context)


def delete_post(request):
    post = get_object_or_404(Post, pk=request.POST.get('post_pk'))
    post.delete()
    return render(request, 'instagramapp/success_delete.html')


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('instagramapp:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'instagramapp/post_edit.html', {'form': form})

def like_post(request):
    post = get_object_or_404(Post, pk=request.POST.get('post_pk'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def follow(request):
    if request.method == "GET":
        relationships= Follow.objects.all()
        user=request.user
        followingUsers = [x.following for x in Follow.objects.filter(follower=user)]
        followerUsers = [x.follower for x in Follow.objects.filter(following=user)]
       
        users= User.objects.exclude(username=user)
       
        query = request.GET.get('q')
        if query:
            users = users.filter(username__icontains=query)
        context = {
            'followingUsers': followingUsers,
            'followerUsers': followerUsers,
            'user': user,
            'users': users, 
            }
      
        return render(request, 'instagramapp/follow.html', context)



def connect(request, operation, pk):
    friend = User.objects.get(pk=pk)
    if operation == 'add':
        Follow.make_friend(request.user, friend )
    elif operation == 'remove':
        Follow.loose_friend(request.user, friend )
    return HttpResponseRedirect(reverse('instagramapp:follow'))

def user_profile(request):
    posts=Post.objects.filter(user=request.user).order_by('-published_date')
    num_post = Post.objects.filter(user=request.user).count()
    num_following = Follow.objects.filter(follower=request.user).count()
    num_followers = Follow.objects.filter(following=request.user).count()
    context = {
        'posts': posts, 
        'num_post': num_post,
        'num_following': num_following,
        'num_followers': num_followers
        }
    return render(request, 'instagramapp/profile.html', context)


def edit_profile(request):
    if request.method == "POST":
        form = EditUserForm(request.POST, instance=request.user)
        profile_form = EditUserProfileForm(request.POST, request.FILES or None, instance=request.user.profile)  # request.FILES is show the selected image or file
        if form.is_valid() and profile_form.is_valid():
            user_form = form.save()
            custom_form = profile_form.save(False)
            custom_form.user = user_form
            custom_form.save()
            return redirect(reverse('instagramapp:user_profile'))
    else:
        form = EditUserForm(instance=request.user)
        profile_form = EditUserProfileForm(instance=request.user.profile)
        args = {}
        # args.update(csrf(request))
        args['form'] = form
        args['profile_form'] = profile_form
        return render(request, 'instagramapp/edit_profile.html', {'form': form, "profile_form": profile_form} )

# REST FRAMEWORK API
class UserProfileView(generics.RetrieveAPIView):
    permission_classes = (IsAuthorOrReadOnly,)
    queryset = get_user_model()
    serializer_class = UserSerializer


class UserViewSet(viewsets.ModelViewSet):
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer

instagramapp/templates/instagramapp/base.html
{% load static %}

<head>
    <title>Instagram</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css" />
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans+Condensed&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/instagram.css' %}" />
</head>

<body>
    <div class="page-header">
        <h1><a href="{% url 'instagramapp:post_list' %}">Instagram</a></h1>
        <div class="top-menu-rigth">
          {% if user.is_authenticated %}
            <a href="{% url 'instagramapp:post_new' %}" class="top-menu"><i class="glyphicon glyphicon-plus"></i></a> {% endif %}
          
              <a href="{% url 'instagramapp:user_profile' %}" class="top-menu"> 
                <i class="glyphicon glyphicon-user"></i>
            </a>
            <a href="{% url 'chatapp:chat' %}" class="top-menu"><i class="glyphicon glyphicon-comment"></i></a> 
           
            <a class="top-menu" href="{% url 'usersapp:password_change' %}"><h2>Change password</h2></a> 
            <a class="top-menu" href="{% url 'usersapp:logout' %}"><h2>Log out</h2></a> 
            
        </div>
    </div>
    <div class="content container">
        <div class="row">
            
                {% block content %} 
                {% endblock %}
           
        </div>
    </div>
</body>

instagramapp/templates/instagramapp/edit_profile.html
{% extends 'instagramapp/base.html' %} 
{% load static %}

{% block content%}
<div class="centeredForm">
<h2>Edit profile</h2>
{% load crispy_forms_tags %}
  <form method="post" class="createPostForm" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
        {{ form| crispy }}
        {{ profile_form| crispy }}
       
        </table>
         {% if user.profile.profile_image %}
             <img id="output"  class="userImage editProfile" src="{{ user.profile.profile_image.url }}" />
              <img id="output"  class="userImage editProfile"  />
             {% else %}
             <img id="output"  class="userImage editProfile"  /> 
             {% endif %}
            
           
        
         <button type="submit" class="button"> Save </button>
    </form>

</div>
 <script> 
const input = document.getElementById("id_profile_image")
input.addEventListener("change", function(event) {
     var file = event.target.files[0]           
    var reader = new FileReader();
    reader.onload = function(){
      var dataURL = reader.result;
      var output = document.getElementById('output');
      output.src = dataURL;
    };
    reader.readAsDataURL(input.files[0]);
}) </script> 
{% endblock%}

instagramapp/templates/instagramapp/follow.html
{% extends "instagramapp/base.html" %} 
{% load static %}


{% block content %}
<div class="tab">
  <button class="tablinks" onclick="openTab(event, 'Following')">Folowing</button>
  <button class="tablinks" onclick="openTab(event, 'Followers')">Followers</button>
    <button class="tablinks active"  onclick="openTab(event, 'Search')">Search</button>
</div>

 <div id="Following" class="tabcontent">

    {% for followingUser in followingUsers%}
    <div class='postHeader' style="justify-content: space-between">
    <div class='postHeader'>
        {% if followingUser.profile.profile_image %}
            <img class="userImage" src="{{ followingUser.profile.profile_image.url }}"/>
             {% else %}
            <img class="userImage" src="{% static "img/icon.jpeg" %}"/>
            {% endif %}
       <h1>{{ followingUser}}</h1>
        </div>
  <a href="{% url 'instagramapp:connect' operation='remove' pk=followingUser.pk %}"> <button class="button"> Unfollow</button></a>
    
    
        </div>
    {% endfor %}
    </div>
  
   
    <div id="Followers" class="tabcontent">
   
     {% for followerUser in followerUsers%}
    <div class='postHeader' style="justify-content: space-between">
    <div class='postHeader'>
        {% if followerUser.profile.profile_image %}
            <img class="userImage" src="{{ followerUser.profile.profile_image.url }}"/>
             {% else %}
            <img class="userImage" src="{% static "img/icon.jpeg" %}"/>
            {% endif %}
       <h1>{{ followerUser }}</h1>
       </div>
       {% if followerUsernot in followingUsers %}
  <a href="{% url 'instagramapp:connect' operation='add' pk=followerUser.pk %}"> <button class="button"> Follow</button></a>
       {% else %}
        <a href="{% url 'instagramapp:connect' operation='remove' pk=followerUser.pk %}"> <button class="button"> Unfollow</button></a>
       {% endif %}
        </div>
    {% endfor %} 
    </div>

     <div id="Search" class="tabcontent">
     <form method="GET" action="">
     <input type="text" placeholder="Search user" name="q" value="{{ request.GET.q }}" />
      <button type="sybmit" class="button"> Search</button>
      </form>
    {% for instagramUser in users %}
    <div class='postHeader' style="justify-content: space-between">
    <div class='postHeader'>
        {% if instagramUser.profile.profile_image %}
            <img class="userImage" src="{{ instagramUser.profile.profile_image.url }}"/>
             {% else %}
            <img class="userImage" src="{% static "img/icon.jpeg" %}"/>
            {% endif %}
       <h1>{{ instagramUser.username }}</h1>
       </div>


         {% if instagramUser in followingUsers %}
           <a href="{% url 'instagramapp:connect' operation='remove' pk=instagramUser.pk %}"> <button class="button"> Unfollow</button></a>
          
       {% else %}
        <a href="{% url 'instagramapp:connect' operation='add' pk=instagramUser.pk %}"> <button class="button"> Follow</button></a>
          
       {% endif %} 

     </div>   
    {% endfor %}
     
   
    </div>
    <script>
function openTab(evt, tabName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  defaultActive = document.getElementById("activeContent")
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";}
  
  tablinks = document.getElementsByClassName("tablinks");

  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(tabName).style.display = "block";
  evt.currentTarget.className += "active";
}
</script>
{% endblock %}

instagramapp/templates/instagramapp/index.html
{% extends "instagramapp/base.html" %} 
{% load static %}


{% block content %}
    {% for post in posts %}
<div class="col-md-8">
         <div class="post">
         <div class="postHeaderContainer">
          
            <div class='postHeader'>
            {% if post.user.profile.profile_image %}
            <img class="userImage" src="{{ post.user.profile.profile_image.url }}"/>
             {% else %}
            <img class="userImage" src="{% static "img/icon.jpeg" %}"/>
            {% endif %}
             <h2>
            {{ post.user }}
            </h2>
             </div> 
            
             <div class="date">
            {{ post.published_date }}
            </div>
             </div>     
            {% if post.image %}
            <div>
            <a href="{% url 'instagramapp:post_detail' pk=post.pk  %}">
            <img class="image" src="{{ post.image.url }}" alt="img" > 
            </a>
            </div>
            {% endif %}
            <div>
              <form action="{% url 'instagramapp:like_post'%}" class="createPostForm" method="POST" > 
             {% csrf_token %} 
             
           
             {% if post.is_liked %}
            
             <button type="submit" name="post_pk" value="{{ post.pk }}" class="btn"> <span style="font-size: 2em; color: red" class="glyphicon glyphicon-heart"></span></button>
             {% else %}
              <button type="submit" name="post_pk" value="{{ post.pk }}" class="btn"> <span style="font-size: 2em;" class="glyphicon glyphicon-heart"></span></button>
              {% endif %}
              {{ post.total_likes }} Like{{post.total_likes|pluralize}} 
           <span class="post-title">{{ post.title | linebreaksbr }}</span>
            </form> 
            </div>
        </div>
        </div>
    {% endfor %} 
{% endblock %}

instagramapp/templates/instagramapp/post_detail.html
{% extends "instagramapp/base.html" %} 
 {% load static %}
{% block content %}
<div class="post">
<div class="postHeaderContainer">
  <div class='postHeader'>
            {% if post.user.profile.profile_image %}
            <img class="userImage" src="{{ post.user.profile.profile_image.url }}"/>
             {% else %}
            <img class="userImage" src="{% static "img/icon.jpeg" %}"/>
            {% endif %}
             <h2>
            {{ post.user }}
            </h2>
             </div> 
             <div class="date">
            {{ post.published_date }}
            </div>
             </div>  
             
     {% if post.image %}
            <img src="{{ post.image.url }}" alt="img" class="image"> 
            {% endif %}
            <div class="postHeaderContainer ">
             <form action="{% url 'instagramapp:like_post'%}" method="POST" > 
             {% csrf_token %} 
             <div> {{ total_likes }} Like{{total_likes|pluralize}}</div>
             
             {% if is_liked %}
             <button type="submit" name="post_pk" value="{{ post.pk }}" class="btn"> <span style="font-size: 2em; color: red" class="glyphicon glyphicon-heart"></span></button>
             {% else %}
              <button type="submit" name="post_pk" value="{{ post.pk }}" class="btn"> <span style="font-size: 2em;" class="glyphicon glyphicon-heart"></span></button>
              {% endif %}
              <span class="post-title">{{ post.title | linebreaksbr }}</span>
              {% if post.user == user %}
            </form> 
                <form action="{% url 'instagramapp:delete_post'%}" method="POST" > 
             {% csrf_token %} 
             <button type="submit" name="post_pk" value="{{ post.pk }}" class="btn"> <span style="font-size: 2em" class="glyphicon glyphicon-trash"></span></button>
            </form> 
            {% endif %} 
            </div>
    </div>
</div>
{% endblock %}

instagramapp/templates/instagramapp/post_edit.html
{% extends 'instagramapp/base.html' %} 
{% block content%}
<div class="centeredForm">
<h2>New post</h2>
<form method="POST"  class="createPostForm" enctype='multipart/form-data'>
    {% csrf_token %} {{ form.as_p }}
    <img id="output" width="400px"/>
    <button type="submit" class="button"> Save </button>
</form>
</div>
<script> 
const input = document.getElementById("id_image")
input.addEventListener("change", function(event) {
  
     var file = event.target.files[0]           
       var reader = new FileReader();
    reader.onload = function(){
      var dataURL = reader.result;
      var output = document.getElementById('output');
      output.src = dataURL;
    };
    reader.readAsDataURL(input.files[0]);
}) </script>
{% endblock%}

instagramapp/templates/instagramapp/profile.html
 {% extends "instagramapp/base.html" %} 
 {% load static %}

        {% block content %} 

            <div class="userContainer"> 
            <div>
            <div class="profileInfoContainer">
                <div >
                {% if user.profile.profile_image %}
                <img class="userImage profile" src="{{ user.profile.profile_image.url }}"/>
                {% else %}
                <img class="userImage profile" src="{% static "img/icon.jpeg" %}"/>
                {% endif %} 
                </div>
                <div>
                <h3>{{user.username}}</h3>
                {{user.first_name}} {{user.last_name}}
                <p>{{user.profile.bio}}</p>
                </div>
            </div>
           <a href="{% url 'instagramapp:edit_profile' %}"> <button class="button">Edit profile</button></a>
            </div>
            <div class="profileRightContainer">
            <div class="statisticContainer"> <h3>posts</h3>  {{ num_post}} </div>
            <a href="{% url 'instagramapp:follow' %}"> <div class="statisticContainer"> <h3>followers</h3>  {{ num_followers}} </div> </a>
             <a href="{% url 'instagramapp:follow' %}"> <div class="statisticContainer"> <h3>following</h3>  {{ num_following}} </div> </a>
            </div>
            </div>
                <div class="profileImageContainer">
                {% for post in posts %}
      
                <div class="postProfile">
                
                    {% if post.image %}
                     <a href="{% url 'instagramapp:post_detail' pk=post.pk  %}">
                    <img src="{{ post.image.url }}" alt="img" > {% endif %}
                    </a>
                    <p>{{ post.text | linebreaksbr }}</p>
                </div>
               
                {% endfor %}
                  </div>
                 {% endblock %}
               

instagramapp/templates/instagramapp/success_delete.html
 {% extends "instagramapp/base.html" %} 
 {% load static %}

        {% block content %} 
        <div class="centeredForm">
        <h1> Poof! The post was deleted! </h1>
        <a href="{% url 'instagramapp:user_profile' %}"> Go back to profile >>> </a>
        </div>
        {% endblock%}